# NumPy Master Notebook

A complete, hands-on notebook covering core to advanced NumPy concepts for data science, machine learning, interviews, and real-world practice.

**How to use this notebook**
- Run every code cell.
- Change values and shapes to observe behavior.
- Repeat tricky sections such as broadcasting, reshaping, indexing, and linear algebra.
- Use this as both a study notebook and a revision guide.

## 1. Setup
Import NumPy and check the installed version.

In [3]:
import numpy as np
np.__version__

'1.26.4'

## 2. Why NumPy matters
NumPy provides fast n-dimensional arrays and vectorized operations. It is the computational foundation under much of the Python data stack, especially Pandas, SciPy, scikit-learn, and many ML workflows.

## 3. Creating arrays
Learn the most important ways to create arrays from Python objects and helper functions.

In [95]:
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.zeros((2, 3))
d = np.ones((3, 2))
e = np.full((2, 2), 7)
f = np.eye(4)
g = np.arange(0, 10, 2)
h = np.linspace(0, 1, 5)

h

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## 4. Array attributes
These are the first attributes you should inspect whenever you receive an unfamiliar array.

In [8]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
{
    'ndim': arr.ndim,
    'shape': arr.shape,
    'size': arr.size,
    'dtype': arr.dtype,
    'itemsize': arr.itemsize,
    'nbytes': arr.nbytes
}

{'ndim': 2,
 'shape': (2, 3),
 'size': 6,
 'dtype': dtype('int32'),
 'itemsize': 4,
 'nbytes': 24}

## 5. Data types and type casting
Dtypes matter in memory usage, precision, and machine learning compatibility.

In [10]:
x = np.array([1, 2, 3], dtype=np.int32)
y = x.astype(np.float64)
z = np.array([1.2, 3.7, 5.9]).astype(int)

x.dtype, y.dtype, z

(dtype('int32'), dtype('float64'), array([1, 3, 5]))

## 6. Indexing and slicing
Mastering indexing is essential because almost every real NumPy task depends on selecting the right subset of data.

In [12]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

result = {
    'arr1[0]': arr1[0],
    'arr1[-1]': arr1[-1],
    'arr1[1:4]': arr1[1:4],
    'arr2[0, 1]': arr2[0, 1],
    'arr2[:, 1]': arr2[:, 1],
    'arr2[1:, :2]': arr2[1:, :2]
}
result

{'arr1[0]': 10,
 'arr1[-1]': 50,
 'arr1[1:4]': array([20, 30, 40]),
 'arr2[0, 1]': 2,
 'arr2[:, 1]': array([2, 5, 8]),
 'arr2[1:, :2]': array([[4, 5],
        [7, 8]])}

## 7. Views vs copies
This is one of the most important beginner-to-intermediate topics. A slice usually creates a view, not an independent copy.

In [14]:
base = np.array([1, 2, 3, 4, 5])
view = base[1:4]
copy = base[1:4].copy()

view[0] = 999
copy[0] = -100

base, view, copy

(array([  1, 999,   3,   4,   5]),
 array([999,   3,   4]),
 array([-100,    3,    4]))

## 8. Reshaping arrays
Reshaping appears everywhere in data preprocessing and ML input preparation.

In [16]:
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
flattened = reshaped.flatten()
raveled = reshaped.ravel()
transposed = reshaped.T

arr, reshaped, flattened, raveled, transposed

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]))

## 9. Combining and splitting arrays
These operations are useful when engineering features or preparing train/test style structures manually.

In [18]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

v = np.vstack([a, b])
h = np.hstack([a, b])
split_v = np.vsplit(v, 2)
split_h = np.hsplit(h, 2)

v, h, split_v, split_h

(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 array([[1, 2, 5, 6],
        [3, 4, 7, 8]]),
 [array([[1, 2],
         [3, 4]]),
  array([[5, 6],
         [7, 8]])],
 [array([[1, 2],
         [3, 4]]),
  array([[5, 6],
         [7, 8]])])

## 10. Broadcasting
Broadcasting lets NumPy operate on arrays of different but compatible shapes without manual loops.

In [20]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
result = a + b
result

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

### Broadcasting rules
1. Compare shapes from the rightmost dimension.
2. Dimensions are compatible if they are equal or one of them is 1.
3. If not compatible, NumPy raises an error.

In [5]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30, 40])
try:
    a + b
except Exception as e:
    print(type(e).__name__, '-', e)

## 11. Vectorized arithmetic
Vectorization replaces slow Python loops with efficient compiled operations.

In [24]:
arr = np.array([1, 2, 3, 4])
operations = {
    'add_5': arr + 5,
    'times_10': arr * 10,
    'squared': arr ** 2,
    'comparison': arr > 2
}
operations

{'add_5': array([6, 7, 8, 9]),
 'times_10': array([10, 20, 30, 40]),
 'squared': array([ 1,  4,  9, 16]),
 'comparison': array([False, False,  True,  True])}

## 12. Universal functions (ufuncs)
Ufuncs are optimized element-wise functions built into NumPy.

In [26]:
arr = np.array([1, 4, 9, 16])
{
    'sqrt': np.sqrt(arr),
    'log': np.log(arr),
    'sin': np.sin(arr),
    'exp': np.exp(arr / 10)
}

{'sqrt': array([1., 2., 3., 4.]),
 'log': array([0.        , 1.38629436, 2.19722458, 2.77258872]),
 'sin': array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332]),
 'exp': array([1.10517092, 1.4918247 , 2.45960311, 4.95303242])}

## 13. Aggregations and axis logic
Understanding `axis` is critical. `axis=0` means operate down rows, `axis=1` means operate across columns.

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
{
    'sum_all': np.sum(arr),
    'sum_axis0': np.sum(arr, axis=0),
    'sum_axis1': np.sum(arr, axis=1),
    'mean_axis0': np.mean(arr, axis=0),
    'max_axis1': np.max(arr, axis=1),
    'std_all': np.std(arr)             
}

{'sum_all': 21,
 'sum_axis0': array([5, 7, 9]),
 'sum_axis1': array([ 6, 15]),
 'mean_axis0': array([2.5, 3.5, 4.5]),
 'max_axis1': array([3, 6]),
 'std_all': 1.707825127659933}

## 14. Boolean masking and filtering
This is one of the most practical NumPy skills for cleaning and selecting data.

In [30]:
arr = np.array([12, 5, 18, 7, 25, 3])
mask = arr > 10
filtered = arr[mask]
arr[(arr > 5) & (arr < 20)], mask, filtered

(array([12, 18,  7]),
 array([ True, False,  True, False,  True, False]),
 array([12, 18, 25]))

## 15. Conditional logic with `np.where`
A common feature-engineering pattern.

In [32]:
scores = np.array([35, 72, 88, 49, 91])
labels = np.where(scores >= 50, 'Pass', 'Fail')
labels

array(['Fail', 'Pass', 'Pass', 'Fail', 'Pass'], dtype='<U4')

## 16. Sorting, searching, and unique values
These tools are used frequently in preprocessing and exploratory analysis.

In [34]:
arr = np.array([5, 2, 9, 2, 1, 8])
{
    'sorted': np.sort(arr),
    'argsort': np.argsort(arr),
    'unique': np.unique(arr),
    'where_gt_4': np.where(arr > 4),
    'argmax': np.argmax(arr),
    'argmin': np.argmin(arr)
}

{'sorted': array([1, 2, 2, 5, 8, 9]),
 'argsort': array([4, 1, 3, 0, 5, 2], dtype=int64),
 'unique': array([1, 2, 5, 8, 9]),
 'where_gt_4': (array([0, 2, 5], dtype=int64),),
 'argmax': 2,
 'argmin': 4}

## 17. Set operations
Useful when comparing categories, IDs, or deduplicated arrays.

In [36]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7])
{
    'union': np.union1d(a, b),
    'intersection': np.intersect1d(a, b),
    'difference_a_b': np.setdiff1d(a, b),
    'difference_b_a': np.setdiff1d(b, a)
}

{'union': array([1, 2, 3, 4, 5, 6, 7]),
 'intersection': array([4, 5]),
 'difference_a_b': array([1, 2, 3]),
 'difference_b_a': array([6, 7])}

## 18. Random module basics
This matters for simulation, bootstrapping, train-test experiments, and ML reproducibility.

In [38]:
rng = np.random.default_rng(42)
ints = rng.integers(1, 10, size=5)
floats = rng.random(5)
normal = rng.normal(loc=0, scale=1, size=5)
choice = rng.choice([10, 20, 30, 40], size=6, replace=True)

ints, floats, normal, choice

(array([1, 7, 6, 4, 4], dtype=int64),
 array([0.69736803, 0.09417735, 0.97562235, 0.7611397 , 0.78606431]),
 array([-0.01680116, -0.85304393,  0.87939797,  0.77779194,  0.0660307 ]),
 array([40, 20, 40, 30, 20, 20]))

## 19. Linear algebra basics
These operations connect directly to machine learning, optimization, and transformations.

In [40]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
v = np.array([1, 2])

{
    'dot_product': np.dot(v, v),
    'matrix_multiply': A @ B,
    'determinant': np.linalg.det(A),
    'inverse': np.linalg.inv(A),
    'eigenvalues': np.linalg.eigvals(A)
}

{'dot_product': 5,
 'matrix_multiply': array([[19, 22],
        [43, 50]]),
 'determinant': -2.0000000000000004,
 'inverse': array([[-2. ,  1. ],
        [ 1.5, -0.5]]),
 'eigenvalues': array([-0.37228132,  5.37228132])}

## 20. Statistics with NumPy
NumPy supports many of the statistical operations you need before moving into Pandas and SciPy.

In [42]:
data = np.array([12, 15, 14, 10, 18, 20, 22, 17, 19, 21])
{
    'mean': np.mean(data),
    'median': np.median(data),
    'variance': np.var(data),
    'std_dev': np.std(data),
    'percentile_25': np.percentile(data, 25),
    'percentile_75': np.percentile(data, 75)
}

{'mean': 16.8,
 'median': 17.5,
 'variance': 14.16,
 'std_dev': 3.7629775444453557,
 'percentile_25': 14.25,
 'percentile_75': 19.75}

## 21. Missing values and NaN-aware functions
NumPy often represents missing numeric data using `np.nan`. Standard aggregation functions can propagate NaN, so use the `nan*` family when appropriate.

In [44]:
arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan])
{
    'regular_mean': np.mean(arr),
    'nanmean': np.nanmean(arr),
    'nansum': np.nansum(arr),
    'isnan': np.isnan(arr)
}

{'regular_mean': nan,
 'nanmean': 2.3333333333333335,
 'nansum': 7.0,
 'isnan': array([False, False,  True, False,  True])}

## 22. File input and output
These functions are useful when saving numerical arrays and loading quick datasets.

In [46]:
sample = np.arange(1, 7).reshape(2, 3)
np.save('sample_array.npy', sample)
loaded = np.load('sample_array.npy')
loaded

array([[1, 2, 3],
       [4, 5, 6]])

## 23. Performance intuition
Vectorized NumPy operations are usually much faster than Python loops for large numeric data.

In [48]:
arr = np.arange(1_000_000)
vectorized = np.sum(arr * 2)
vectorized

-728379968

## 24. Practical data science mini-examples
Small examples show how NumPy appears in feature scaling, cleaning, and matrix-style data preparation.

In [50]:
heights = np.array([150, 160, 170, 180, 190], dtype=float)
mean = heights.mean()
std = heights.std()
z_scores = (heights - mean) / std
min_max = (heights - heights.min()) / (heights.max() - heights.min())

{
    'z_scores': z_scores,
    'min_max_scaled': min_max
}

{'z_scores': array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356]),
 'min_max_scaled': array([0.  , 0.25, 0.5 , 0.75, 1.  ])}

In [51]:
features = np.array([[170, 65], [180, 80], [160, 55], [175, 72]])
weights = np.array([0.3, 0.7])
prediction_scores = features @ weights
prediction_scores

array([ 96.5, 110. ,  86.5, 102.9])

## 25. Common beginner mistakes
- Confusing Python lists with NumPy arrays.
- Forgetting that slices often return views.
- Using incompatible shapes in broadcasting.
- Ignoring dtype conversion.
- Forgetting the meaning of `axis`.
- Mixing row and column expectations while reshaping.

## 26. Practice tasks
Try these before moving to Pandas.

1. Create a 4x4 array from 1 to 16.
2. Extract the second column.
3. Replace all even numbers with 0 using `np.where`.
4. Compute row sums and column means.
5. Reshape a 1D array of length 12 into shapes `(3, 4)` and `(2, 6)`.
6. Create two arrays and demonstrate valid broadcasting.
7. Find unique values and counts in an array.
8. Standardize a numeric array using z-score scaling.
9. Compute dot product and matrix multiplication examples.
10. Create a random array and filter values above the mean.

## 27. Interview-focused quick revision
- What is the difference between a Python list and a NumPy array?
- What is broadcasting?
- Difference between `flatten()` and `ravel()`?
- Difference between a copy and a view?
- What does `axis=0` and `axis=1` mean?
- What is dtype and why does it matter?
- How is `np.where` used?
- What is vectorization and why is it fast?
- Difference between `arr * arr` and `arr @ arr`?
- How do you handle missing numeric values in NumPy?

## 28. Next step after NumPy
After you are comfortable with these topics, move to Pandas for tabular data manipulation, cleaning CSV files, grouping, merging, and EDA workflows.