# numpy

**Install Numpy First**

pip install numpy

In [7]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np # alias

In [9]:
print(np.__version__)

1.26.4


In [10]:
my_list=[1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


In [11]:
# my_list=my_list*2
my_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

numpy array 

In [13]:
array=np.array([1,2,3,4,5])

In [14]:
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
array*2

array([ 2,  4,  6,  8, 10])

**Multi Dimensional array**

In [17]:
array1=np.array([[1,2,3,4],[5,6,7,8]])
array2=np.array([[1],[2]])

In [18]:
print(array1.shape)
print(array2.shape)

(2, 4)
(2, 1)


In [19]:
array1*array2

array([[ 1,  2,  3,  4],
       [10, 12, 14, 16]])

# Creating arrays

In [21]:
# Creating arrays

a=np.array([1,2,3,4]) # 1-Dimensional array
a

array([1, 2, 3, 4])

In [22]:
b=np.array([[1,2,3],[4,5,6]]) # 2-Dimensional array
b

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
c=np.zeros((2,3)) # creates 2 x 3 matrix with items 0
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
d=np.ones((3,2)) # creates 3 x 2 matrix with items 1
d

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
e=np.full((2,3),6) # creates 2 x 3 matrix with items 6 (any number that we specify)
e

array([[6, 6, 6],
       [6, 6, 6]])

In [26]:
f=np.eye(4) # creates a 4 x 4 matrix with num '1' in diagonal
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
g=np.arange(0,10,2) # creates an array by mentioning range values (start,stop,step)
g

array([0, 2, 4, 6, 8])

In [28]:
h=np.linspace(0,1,5) # Creates evenly spaced values in a 1x1 matrix (start,stop,total_values)
h

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Array attributes

In [30]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

In [31]:
dic={
    'ndim': arr.ndim, # returns the dimension of the array
    
    'shape': arr.shape, # returns the shape of the array (ex:- 2,3 for 2x3 matrix)
    
    'size': arr.size, # returns the size of the array (number of elements in array)
    
    'dtype': arr.dtype, # returns the datatype of the array
    
    'itemsize': arr.itemsize, # returns the array length (ex:- 4 i.e byte size of int datatype)
    
    'nbytes': arr.nbytes # returns the product of (arr.size x arr.itemsize)
}

In [32]:
dic

{'ndim': 2,
 'shape': (2, 3),
 'size': 6,
 'dtype': dtype('int32'),
 'itemsize': 4,
 'nbytes': 24}

# Data types and type casting

Dtypes matter in memory usage, precision, and machine learning compatibility.

In [34]:
x = np.array([1, 2, 3], dtype=np.int32)
x

array([1, 2, 3])

In [35]:
x = np.array([1, 2, 3], dtype=np.float64)
x

array([1., 2., 3.])

In [36]:
y=x.astype(np.int32)
y

array([1, 2, 3])

In [37]:
y = x.astype(np.float64)
y

array([1., 2., 3.])

In [38]:
z=np.array([1.2,3.7,5.9])
z

array([1.2, 3.7, 5.9])

In [39]:
z.astype(int)

array([1, 3, 5])

In [40]:
z.astype(str)

array(['1.2', '3.7', '5.9'], dtype='<U32')

# Indexing and slicing

Mastering indexing is essential because almost every real NumPy task depends on selecting the right subset of data.

In [42]:
arr1 = np.array([10, 20, 30, 40, 50])

In [163]:
arr1[0]

10

In [44]:
arr1[-1]

50

In [45]:
arr1[0:4]

array([10, 20, 30, 40])

In [46]:
arr1[:]

array([10, 20, 30, 40, 50])

In [47]:
arr1[::-1]

array([50, 40, 30, 20, 10])

In [48]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [165]:
arr2[0][0]

1

In [50]:
arr2[:,1]

array([2, 5, 8])

In [51]:
arr2[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr2[0,1] # instead of using two [0][1] we can use single [] and mention the index separated by camma

2

In [53]:
arr2[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [54]:
arr2[1:,:2]

array([[4, 5],
       [7, 8]])

# Views vs copies
This is one of the most important beginner-to-intermediate topics. A slice usually creates a view, not an independent copy.

In [56]:
base = np.array([1, 2, 3, 4, 5])
view = base[1:4]
view

array([2, 3, 4])

In [57]:
view[0]=999
print(view)

[999   3   4]


In [58]:
copy=base[1:4].copy()
copy

array([999,   3,   4])

In [59]:
copy[0]=-100
copy

array([-100,    3,    4])

# Reshaping arrays
Reshaping appears everywhere in data preprocessing and ML input preparation.

In [61]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
reshaped = arr.reshape(3, 4)
reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
reshaped=arr.reshape(2,6)
reshaped

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [64]:
reshaped=arr.reshape(4,3)
reshaped

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [65]:
new_reshape=reshaped.reshape(1,12)
new_reshape

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [66]:
flattened = reshaped.flatten()
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

**order (optional) — specifies the reading order of elements:**

- 'C' → Row-major (C-style) order (default) — read row by row.
- 'F' → Column-major (Fortran-style) order — read column by column.
- 'A' → Fortran order if array is Fortran-contiguous, else C order.
- 'K' → Flatten in the order elements occur in memory.

In [68]:
reshaped

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
flattened = reshaped.flatten('C')
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
reshaped

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [71]:
flattened = reshaped.flatten('F')
flattened

array([ 0,  3,  6,  9,  1,  4,  7, 10,  2,  5,  8, 11])

In [72]:
flattened = reshaped.flatten('A')
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
flattened = reshaped.flatten('K')
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

The .ravel() function in NumPy is used to return a contiguous flattened array from a given multi-dimensional array. This means it converts the input array into a one-dimensional array while maintaining the same data type. A copy of the data is made only if necessary, making it efficient in terms of memory usage.

In [75]:
raveled = reshaped.ravel()
raveled

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
reshaped

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In NumPy, the .T attribute is used to transpose an array, which means flipping its axes. For example, rows become columns and vice versa. However, .T does not create a copy of the array; instead, it returns a view of the original array with transposed axes.

In [78]:
transposed = reshaped.T
transposed

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

# Combining and splitting arrays
These operations are useful when engineering features or preparing train/test style structures manually.

numpy.hstack stacks arrays horizontally, meaning it appends arrays along the columns. This is particularly useful when you want to combine arrays side-by-side. For hstack to work, the arrays must have the same number of rows.

In [81]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [82]:
v=np.vstack([a,b])
v

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [83]:
h=np.hstack([a,b])
h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [84]:
split_v=np.vsplit(v,2)
split_v

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [85]:
split_v=np.vsplit(v,4)
split_v

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]

In [86]:
split_h=np.hsplit(h,2)
split_h

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [87]:
split_h=np.hsplit(v,2)
split_h

[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]

# Practice tasks

In [161]:
#1. Create a 4x4 array from 1 to 16.

array= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
np.shape(array)

(4, 4)

In [183]:
#2. Extract the second column.

array[0:,1:2]

array([[ 2],
       [ 6],
       [10],
       [14]])

In [191]:
#3. Replace all even numbers with 0 using np.where

even=np.where(0 if array%2==0 else array)
even

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()