# Part -1 Basics

In [3]:
import numpy as np #it is used to import numpy and np is the alias 

## Creating an Array of N-Dimensions

In [32]:
l=[1,2,3,4,5]  # basic using list which represents a 1-D array
type(l)

list

In [16]:
a=np.array([1,2,3,4,5])  # Creates a 1-D array
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])  # Creates a 2-D array
c=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])  # Creates a 3-D array

In [26]:
print("1-D Array")
print(a)
print("2-D Array")
print(b)
print("3-D Array")
print(c)

1-D Array
[1 2 3 4 5]
2-D Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3-D Array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [30]:
type(a)

numpy.ndarray

In [38]:
print(a.size)           # Returns the size, i.e. no. of elements in the array
print(b.size)
print(c.size)

5
10
15


In [42]:
print(a.shape)           # Returns the rows & cols, i.e. no. of rows,cols in an array
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [44]:
print(a.dtype)           # Returns the datatype of elements in the array
print(b.dtype)
print(c.dtype)

int32
int32
int32


In [50]:
d=np.array([[1,2,3,4.6,5],[6,7.7,8,9,10.2],[11,12.4,13,14.6,15]])

In [52]:
type(d)

numpy.ndarray

In [56]:
d.dtype


dtype('float64')

In [58]:
d

array([[ 1. ,  2. ,  3. ,  4.6,  5. ],
       [ 6. ,  7.7,  8. ,  9. , 10.2],
       [11. , 12.4, 13. , 14.6, 15. ]])

In [62]:
d.transpose()

array([[ 1. ,  6. , 11. ],
       [ 2. ,  7.7, 12.4],
       [ 3. ,  8. , 13. ],
       [ 4.6,  9. , 14.6],
       [ 5. , 10.2, 15. ]])

## Creating an array with random elements of specific dtype

In [77]:
# Syntax : - np.empty((rows,cols),dtype="int")

a=np.empty((4,4),dtype='int')  # Creates a 2-D Array
print(a)

[[4128860 6029375 3801155 5570652]
 [6619251 7536754 7733340 7077993]
 [7536737 4259932 7340144 6357060]
 [6357108 4980828 6488175 7077985]]


In [99]:
a=np.empty((4,4),dtype='float')  # Creates a 2-D Array
print(a)

[[4.67296746e-307 1.69121096e-306 1.24611266e-306 8.34441742e-308]
 [1.78022342e-306 6.23058028e-307 9.79107872e-307 6.89807188e-307]
 [7.56594375e-307 6.23060065e-307 1.78021527e-306 8.34454050e-308]
 [1.11261027e-306 1.15706896e-306 1.33512173e-306 1.33504432e-306]]


In [106]:
# creating an array with elements of 1
# Syntax : np.ones((rows,cols),dtype)

x=np.ones(6) # creates an array with 6 elements of 1's
x

array([1., 1., 1., 1., 1., 1.])

In [110]:
y=np.ones((2,3),dtype='int')
y

array([[1, 1, 1],
       [1, 1, 1]])

In [116]:
z=np.ones((3,5)) # default dtype is 'float'
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [120]:
# Similar to ones we also have zeros.

# Syntax : np.zeros((rows,cols),dtype)

a=np.zeros(8) # Default dtype is 'float'
a

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [122]:
np.ones((3,5),dtype='str')

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [124]:
np.zeros((3,5),dtype='str') # Unlike ones, here it returns empty

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [128]:
np.ones((3,5),dtype='bool')

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [130]:
np.zeros((3,5),dtype='bool')

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [132]:
#  arange

In [134]:
# Syntax : np.arange(start,stop,step)

a=np.arange(1,20) # default step = 1
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [148]:
a=np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


In [168]:
# reshape
# used to modify the shape of an existing array
# rows X cols should be equal to No. elements present in the existing array

In [150]:
# Syntax: array.reshape(rows,cols)
print(f"a before reshape : {a}")

a=a.reshape((3,3))
print(f"a after reshape : \n{a}")


a before reshape : [ 2  4  6  8 10 12 14 16 18]
a after reshape : 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [164]:
b=np.arange(1,100,2)
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [166]:
b=b.reshape((10,5))
print(b)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]
 [61 63 65 67 69]
 [71 73 75 77 79]
 [81 83 85 87 89]
 [91 93 95 97 99]]


In [170]:
# flatten() and ravel()

# flatten() returns a duplicate copy of original array and modifying doesn't effects the original arr, but consumes extra memory

# ravel() refrences/copy view of the original arr, and modifying leads to modify in the original arr, doesn't consume memory

In [172]:
b=b.flatten()
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [174]:
a=a.ravel()
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

# Part-2

## Slicing array

In [178]:
a=np.arange(1,100,2)
a=a.reshape((10,5))
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [180]:
a[0] # returns the 1st row elements

array([1, 3, 5, 7, 9])

In [182]:
a[4]

array([41, 43, 45, 47, 49])

In [186]:
a[2,4] # returns 4th index element of 2nd index row

29

In [188]:
a[2:5] # returns all the rows from 2nd index till 4th row, 5th is excluded

array([[21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [190]:
a[1:10]

array([[11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [192]:
a[:,3] # returns all the rows of 3rd index col

array([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

In [194]:
a[:, :] # all rows and all cols elements

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [198]:
a[2:5,2] # returns rows from 2-4 of col 2nd index

array([25, 35, 45])

### Mathematical Operations

In [201]:
a=np.arange(0,18).reshape((6,3))
b=np.arange(20,38).reshape((6,3))

In [203]:
print(f"Array a : \n{a} \nArray b :\n{b}")

Array a : 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]] 
Array b :
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [205]:
#using operators

In [207]:
a-b

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [209]:
a+b

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [211]:
a*b

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [213]:
a/b

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [215]:
a%b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [217]:
a//b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [221]:
# Using Functions/methods

In [223]:
np.add(a,b)

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [225]:
np.subtract(a,b)

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [227]:
np.multiply(a,b)

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [229]:
np.divide(a,b)

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [241]:
print(f"Size of a :{a.shape} , Size of b :{b.shape}")

a@b

# We encounter error since the row size of b and col size of a doesn't match and neither of them is 1

Size of a :(6, 3) , Size of b :(6, 3)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 6 is different from 3)

In [247]:
# so we have to reshape b

b=b.reshape((3,6))

In [249]:
# now we can perform dot multiplication i.e. matrix multiplication

a@b

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [251]:
a.dot(b)

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [255]:
b.max()

37

In [257]:
b.min()

20

In [259]:
b.argmax() # Gives the position/index of the max value

17

In [261]:
b.argmin()

0

In [269]:
np.sum(b) 

513

In [271]:
np.sum(b,axis=1) # sum of all the rows

array([135, 171, 207])

In [273]:
np.sum(b,axis=0) # sum of all the cols

array([78, 81, 84, 87, 90, 93])

In [275]:
np.sqrt(b)

array([[4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
        5.        ],
       [5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558,
        5.56776436],
       [5.65685425, 5.74456265, 5.83095189, 5.91607978, 6.        ,
        6.08276253]])

In [277]:
np.log(b)

array([[2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
        3.21887582],
       [3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
        3.4339872 ],
       [3.4657359 , 3.49650756, 3.52636052, 3.55534806, 3.58351894,
        3.61091791]])

In [279]:
np.mean(b)

28.5

In [281]:
np.median(b)

28.5

In [285]:
np.exp(b)

array([[4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
        2.64891221e+10, 7.20048993e+10],
       [1.95729609e+11, 5.32048241e+11, 1.44625706e+12, 3.93133430e+12,
        1.06864746e+13, 2.90488497e+13],
       [7.89629602e+13, 2.14643580e+14, 5.83461743e+14, 1.58601345e+15,
        4.31123155e+15, 1.17191424e+16]])

In [287]:
np.std(b)

5.188127472091127

### Trignometry

In [292]:
import matplotlib.pyplot as plt
plt.style.use('dark_background')

In [294]:
np.pi

3.141592653589793

In [296]:
np.sin(np.pi/2) # 90 degree

1.0

In [312]:
round(np.sin(np.pi/6),2)

0.5

In [314]:
np.cos(np.pi/2)

6.123233995736766e-17

In [316]:
np.tan(np.pi/6)

0.5773502691896257

In [318]:
np.tan(0)

0.0

### Random Function

In [327]:
np.random.random(1) # 1-D array

array([0.82239051])

In [331]:
np.random.random(2) # 1-D array,with 2 elements

array([0.01804523, 0.79345368])

In [333]:
np.random.random((2,3)) # 2-D array

array([[0.36199074, 0.52154526, 0.63955015],
       [0.71473421, 0.05721108, 0.43321324]])

In [335]:
np.random.randint(4)

2

In [337]:
np.random.randint(1,10)

5

In [339]:
np.random.randint(1,10,(2,2))

array([[3, 2],
       [2, 3]])

In [341]:
np.random.randint(1,10,(3,4,5)) # 3-D array

array([[[9, 4, 3, 4, 7],
        [5, 6, 1, 7, 4],
        [5, 6, 8, 3, 5],
        [2, 5, 5, 7, 4]],

       [[8, 6, 9, 2, 9],
        [7, 7, 1, 3, 2],
        [3, 6, 4, 8, 5],
        [7, 1, 6, 4, 7]],

       [[8, 6, 9, 7, 7],
        [7, 1, 9, 2, 6],
        [8, 1, 5, 2, 5],
        [2, 1, 1, 9, 3]]])

In [343]:
np.random.rand(2)

array([0.75658685, 0.08612985])

In [347]:
np.random.rand(2,2) # similar to .random((2,2))

array([[0.44995457, 0.26371925],
       [0.96957146, 0.08116874]])

In [353]:
np.random.randn(2,2) # also includes negative numbers

array([[ 0.94070573, -0.10809627],
       [-0.32576244, -0.8266605 ]])

In [357]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [470]:
np.random.choice(a) # Chooses an element from 'a' randomly

8

### String Operations

In [474]:
s1="My Firstname is Vilas"
s2="My Lastname is Kumar"

In [476]:
print(s1,s2)

My Firstname is Vilas My Lastname is Kumar


In [478]:
np.char.add(s1,s2)

array('My Firstname is VilasMy Lastname is Kumar', dtype='<U41')

In [480]:
np.char.upper(s1)

array('MY FIRSTNAME IS VILAS', dtype='<U21')

In [488]:
np.char.lower(s1)

array('my firstname is vilas', dtype='<U21')

In [490]:
np.char.capitalize(s1)

array('My firstname is vilas', dtype='<U21')

In [492]:
np.char.title(s1)

array('My Firstname Is Vilas', dtype='<U21')

In [496]:
np.char.split(s1)

array(list(['My', 'Firstname', 'is', 'Vilas']), dtype=object)

In [500]:
np.char.split(s1,',')

array(list(['My Firstname is Vilas']), dtype=object)

In [502]:
s3="My Firstname is\nVilas"

In [508]:
np.char.splitlines(s3)

array(list(['My Firstname is', 'Vilas']), dtype=object)

In [510]:
np.char.replace(s1,'Firstname','Name')

array('My Name is Vilas', dtype='<U16')

In [512]:
np.char.center('good bye',20,'*')

array('******good bye******', dtype='<U20')